##################################################
# Hyprland - badsignal's main config
##################################################

# --- Monitors -----------------------------------
monitor=,preferred,auto,1

# --- Source -------------------------------------
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/look.conf
source = ~/.config/hypr/keybinds.conf
#source = ~/.config/hypr/windowrules.conf
#source = ~/.config/hypr/nvidia.conf
